'gitcreate' and 'gitdelete' working with Digital Ocean server

diff --git a/home/max/.bin/gitcreate b/home/max/.bin/gitcreate
--- a/home/max/.bin/gitcreate
+++ b/home/max/.bin/gitcreate
@@ -11,23 +11,48 @@ if [ -d ".git" ]; then
         exit 0
 fi
 
-if [ "$1" == "" ]; then
-        REPOS_NAME=$FOLDER-$TIME
+
+if [ "$1" == "-vm" ]; then
+    SERVER="maxdo:/root/git"
 else
+    SERVER="git@github.com:maxiwell"
+fi
+
+echo "Server: $SERVER"
+
+
+if [ "$1" == "-vm" ]; then
+    if  [ "$2" == "" ]; then
+        REPOS_NAME=$FOLDER-$TIME
+    else
+        REPOS_NAME=$2
+    fi
+else
+    if [ "$1" == "" ]; then
+        REPOS_NAME=$FOLDER-$TIME
+    else
         REPOS_NAME=$1
+    fi
 fi
 
-if [ ! -f /usr/bin/curl ]; then
-        echo "I require \"curl\" but it's not installed.  Aborting."
-        exit 1;
-fi
+echo "Repository: $REPOS_NAME"
 
-curl -sS -L -u 'maxiwell' https://api.github.com/user/repos -d '{"name":"'$REPOS_NAME'","description":"'$PATHFOLDER'"}'  > temp
-badcredentials=`cat temp | grep -c "Bad credentials"`
-rm temp
-if [ "$badcredentials" != 0 ]; then
-        echo "GitHub: Bad credentials. Aborting"
-        exit 1;
+
+if echo "$SERVER" | grep github > /dev/null ; then
+    if [ ! -f /usr/bin/curl ]; then
+            echo "I require \"curl\" but it's not installed.  Aborting."
+            exit 1;
+    fi
+    
+    curl -sS -L -u 'maxiwell' https://api.github.com/user/repos -d '{"name":"'$REPOS_NAME'","description":"'$PATHFOLDER'"}'  > temp
+    badcredentials=`cat temp | grep -c "Bad credentials"`
+    rm temp
+    if [ "$badcredentials" != 0 ]; then
+            echo "GitHub: Bad credentials. Aborting"
+            exit 1;
+    fi
+else
+    ssh maxdo "mkdir /root/git/$REPOS_NAME && cd /root/git/$REPOS_NAME && git --bare init"
 fi
 
 if [  `ls -1 | wc -l` -eq 0 ]; then
@@ -37,7 +62,7 @@ fi
 git init
 git add *
 git commit -m "Initial commit"
-git remote add origin git@github.com:maxiwell/$REPOS_NAME 
+git remote add origin $SERVER/$REPOS_NAME 
 git push -u origin master
 
 
diff --git a/home/max/.bin/gitdelete b/home/max/.bin/gitdelete
--- a/home/max/.bin/gitdelete
+++ b/home/max/.bin/gitdelete
@@ -1,11 +1,29 @@
 #!/bin/bash
 
 
+
 if [ "$1" == "" ]; then
-        echo "Abort. Repository Name not found"
-        exit 0
+        echo "Abort: Input the Name of the Repository"
+        exit 1
 fi
 
+# Get the Repository Name from the current directory
+DIR_RNAME=$(basename $(git remote show -n origin | grep Fetch | cut -d: -f2-))
+if [ $DIR_RNAME != $1 ] ; then
+    echo "This current path ($PWD) does not belong to the Repository '$1'"
+    exit 1
+fi
 
-curl -X DELETE -u 'maxiwell' https://api.github.com/repos/maxiwell/$1 
+if git info | grep github > /dev/null ; then
+    echo "Server: Github.com"
+    echo "Repository: $1"
+    curl -X DELETE -u 'maxiwell' https://api.github.com/repos/maxiwell/$1 
+    rm -rf .git
+else
+    echo "Server: Digital Ocean VM"
+    echo "Repository: $1"
+    ssh maxdo "rm -r /root/git/$1"
+    rm -rf .git
+fi
+
 
